version: '3.8'

services:
  dagster:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dagster-hello-world
    volumes:
      - .:/app
    environment:
      - DAGSTER_HOME=/app
    restart: unless-stopped
    networks:
      - dagster-network

networks:
  dagster-network:
    external: true
    name: ${NETWORK_NAME}

